<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OccupationSeeder extends Seeder
{
    public function run(): void
    {
        $occupations = [
            'Accountant',
            'Actuary',
            'Administrative Assistant',
            'Advertising Manager',
            'Aerospace Engineer',
            'Agricultural Scientist',
            'Agronomist',
            'Air Traffic Controller',
            'Airline Pilot',
            'Animator',
            'Anthropologist',
            'App Developer',
            'Archaeologist',
            'Architect',
            'Art Director',
            'Artist',
            'Attorney / Lawyer',
            'Auditor',
            'Automation Engineer',
            'Biochemist',
            'Biomedical Engineer',
            'Bookkeeper',
            'Business Analyst',
            'Carpenter',
            'Cashier',
            'Chef / Cook',
            'Chemical Engineer',
            'Civil Engineer',
            'Clinical Psychologist',
            'Coach / Trainer',
            'Content Writer / Copywriter',
            'Customer Success Manager',
            'Data Analyst',
            'Data Scientist',
            'Database Administrator',
            'Dentist',
            'Dermatologist',
            'DevOps Engineer',
            'Dietitian / Nutritionist',
            'Editor',
            'Electrician',
            'Environmental Scientist',
            'Event Planner',
            'Executive Assistant',
            'Fashion Designer',
            'Film/Video Director',
            'Financial Analyst',
            'Financial Advisor / Planner',
            'Fitness Instructor',
            'Flight Attendant',
            'Front-End Developer',
            'Full-Stack Developer',
            'Game Developer',
            'General Contractor',
            'Geologist',
            'Graphic Designer',
            'HR Manager',
            'Human Resources Specialist',
            'Illustrator',
            'Industrial Designer',
            'Insurance Agent / Underwriter',
            'Interior Designer',
            'Interpreter / Translator',
            'IT Support Specialist',
            'Journalist',
            'Judge',
            'Librarian',
            'Loan Officer',
            'Machine Learning Engineer',
            'Maintenance Technician',
            'Management Consultant',
            'Marketing Manager',
            'Mechanical Engineer',
            'Medical Assistant',
            'Microbiologist',
            'Network Engineer',
            'Nurse',
            'Occupational Therapist',
            'Office Manager',
            'Operations Manager',
            'Paralegal',
            'Pharmacist',
            'Photographer',
            'Physical Therapist',
            'Plumber',
            'Product Manager',
            'Production Manager',
            'Project Manager',
            'Psychologist',
            'Public Relations Specialist',
            'Quality Assurance Engineer / Tester',
            'Real Estate Agent / Realtor',
            'Receptionist',
            'Research Scientist',
            'Retail Manager',
            'Sales Manager',
            'School Teacher',
            'Secretary',
            'Security Analyst',
            'SEO Specialist',
            'Social Worker',
            'Software Engineer',
            'Sound Engineer',
            'Statistician',
            'Surgeon',
            'Systems Analyst',
            'Tax Consultant',
            'Technical Writer',
            'UX Designer',
            'UI Designer',
            'Urban Planner',
            'Veterinarian',
            'Video Producer',
            'Virtual Assistant',
            'Welder',
            'Writer / Author',
        ];

        $now = now();
        DB::table('occupations')->insert(array_map(function ($name) use ($now) {
            return [
                'name' => $name,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $occupations));
    }
}
