<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $skills = [

            'JavaScript',
            'TypeScript',
            'PHP',
            'Python',
            'Ruby',
            'Java',
            'Kotlin',
            'Swift',
            'Objective-C',
            'C',
            'C++',
            'C#',
            'Go',
            'Rust',
            'HTML',
            'CSS',
            'Sass',
            'Less',
            'Tailwind CSS',
            'Bootstrap',
            'React',
            'Next.js',
            'Angular',
            'Vue.js',
            'Nuxt',
            'Web Components',
            'jQuery',
            'Webpack',
            'Vite',
            'Node.js',
            'Express',
            'NestJS',
            'Laravel',
            'Symfony',
            'Lumen',
            'Django',
            'Flask',
            'Ruby on Rails',
            'Spring',
            '.NET',
            'ASP.NET',
            'React Native',
            'Flutter',
            'Ionic',
            'Android',
            'iOS',
            'SwiftUI',
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'MongoDB',
            'Redis',
            'Elasticsearch',
            'Cassandra',
            'DynamoDB',
            'Firebase',
            'Neo4j',
            'MariaDB',
            'Docker',
            'Kubernetes',
            'CI/CD',
            'GitHub Actions',
            'Jenkins',
            'CircleCI',
            'Terraform',
            'Ansible',
            'Packer',
            'Vagrant',
            'AWS',
            'Azure',
            'Google Cloud Platform',
            'Serverless',
            'Lambda',
            'CloudFormation',
            'UX Design',
            'UI Design',
            'Figma',
            'Sketch',
            'Adobe XD',
            'Photoshop',
            'Illustrator',
            'Accessibility (a11y)',
            'Responsive Design',
            'Interaction Design',
            'Product Management',
            'Roadmapping',
            'Agile',
            'Scrum',
            'Kanban',
            'Jira',
            'Trello',
            'OKRs',
            'Communication',
            'Leadership',
            'Problem Solving',
            'Critical Thinking',
            'Time Management',
            'Teamwork',
            'Customer Success',
            'Negotiation',
            'Presentation',
            'Mentoring',
            'Performance Optimization',
            'Profiling',
            'Caching Strategies',
            'CDN',
            'Image Optimization',
            'Git',
            'Version Control',
            'CI/CD pipelines',
            'Code Review',
            'Pair Programming',
            'Refactoring',
            'Documentation',
            'API Design',
            'Authentication/Authorization',
            'SEO',
            'Growth Hacking',
            'Content Writing',
            'Customer Support',
            'CRM',
            'Blockchain',
            'Smart Contracts',
            'Solidity',
            'DevSecOps',
            'IoT',
            'Edge Computing',
            'Augmented Reality',
            'Virtual Reality',
            'Game Development'
        ];

        $now = now();
        $rows = array_map(function ($name) use ($now) {
            return [
                'name' => $name,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $skills);

        DB::table('skills')->insert($rows);
    }
}
